version: '3'
services:
  client:
    image: cyberark/conjur-cli:5
    entrypoint: sleep
    command: infinity
    environment:
      CONJUR_APPLIANCE_URL:
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
    volumes:
      - $PWD/test:/test

  terraform:
    build:
      context: .
      dockerfile: Dockerfile.terraform

    entrypoint: sleep infinity
    environment:
      CONJUR_APPLIANCE_URL:
      CONJUR_ACCOUNT:
      CONJUR_AUTHN_LOGIN:
      CONJUR_AUTHN_API_KEY:
      CONJUR_SSL_CERTIFICATE:
      TF_LOG: "${TF_LOG:-INFO}"
      TF_VAR_conjur_api_key:
      TF_VAR_conjur_ssl_cert:
    working_dir: /src
    volumes:
      - $PWD:/src
      - $PWD/dist/terraform-provider-conjur_linux_amd64/:/usr/share/terraform/plugins/terraform.example.com/cyberark/conjur/${CONJUR_PLUGIN_VERSION}/linux_amd64/

  goreleaser:
    build:
      context: .
      dockerfile: Dockerfile.goreleaser
    volumes:
      - .:/terraform-provider-conjur
    working_dir: /terraform-provider-conjur
