# Terraform Provider release workflow.
name: Release

on:
  push:
    tags:
      - 'v*'


env:
  CONJUR_USERNAME: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_USERNAME }}
  CONJUR_API_KEY: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_API_KEY }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Publish to Artifactory
      run: |
        ls -lrth

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v5.0.0
      with:
        args: release --clean
      env:
        # GitHub sets the GITHUB_TOKEN secret automatically.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get Jfrog API Token
      uses: cyberark/conjur-action@v2.0.5
      with:
        url: https://conjur-prod-follower.cisco.com:443
        account: cisco
        host_id: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_USERNAME }}
        api_key: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_API_KEY }}
        secrets: it/hci/accounts/artifactory/prod/artifacts/api_key|JFROG_API_TOKEN
        
    - name: Get Artifactory URL
      uses: cyberark/conjur-action@v2.0.5
      with:
        url: https://conjur-prod-follower.cisco.com:443
        account: cisco
        host_id: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_USERNAME }}
        api_key: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_API_KEY }}
        secrets: it/hci/accounts/artifactory/prod/url|ARTIFACTORY_URL

    - name: Get Artifactory Username
      uses: cyberark/conjur-action@v2.0.5
      with:
        url: https://conjur-prod-follower.cisco.com:443
        account: cisco
        host_id: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_USERNAME }}
        api_key: ${{ secrets.CONJUR_PROD_HCI_ACCOUNTS_API_KEY }}
        secrets: it/hci/accounts/artifactory/prod/artifacts/username|JFROG_USERNAME

    - name: Publish to Artifactory
      run: |
        # Use your JFrog Artifactory details and API token for authentication
        # curl -u ${JFROG_USERNAME}:${JFROG_API_TOKEN} -T ~/.terraform.d/plugins/terraform-provider-conjur https://${ARTIFACTORY_URL}/HybridCloudIT/conjur/1.0.0/terraform-provider-conjur_0.0.1_darwin_amd64.zip
        ls -lrth
        ls -lrth ./dist/*
